# version: '3.9'

services:
  emailservice:
    build:
      context: .
      dockerfile: EmailService/Dockerfile
    image: emailservice:latest
    env_file:
      - ./EmailService/.env.example
    depends_on:
      - rabbitmq
      - redis
      # - mailhog
    ports:
      - "8003:8080"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-guest}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-guest}"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:1.0.1
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    restart: unless-stopped

  user_service:
    image: nginx:stable-alpine
    container_name: user_service
    restart: unless-stopped

  template_service:
    image: nginx:stable-alpine
    container_name: template_service
    restart: unless-stopped


volumes:
  rabbitmq_data:
  redis_data:

networks:
  app-network:
    driver: bridge